In [2]:
import pandas as pd
df=pd.read_csv('../data/part5/auto-mpg.csv', header=None)

# 열 이름 지정
df.columns=['mpg', 'cylinders','displacement','horsepower','weight','acceleration','model year','origin','name']
print(df.head(3))

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  


In [3]:
# mpg를 kpl로 변환
mpg_to_kpl=1.60934/3.78541

#mpg열에 0.425를 곱한 결과를 새로운 열에 추가
df['kpl']=df['mpg']*mpg_to_kpl
print(df.head(3))

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   

   origin                       name       kpl  
0       1  chevrolet chevelle malibu  7.652571  
1       1          buick skylark 320  6.377143  
2       1         plymouth satellite  7.652571  


In [4]:
#kpl 열을 소수점 아래 둘째자리에서 반올림
df['kpl']=df['kpl'].round(2)
print(df.head(3))


    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   

   origin                       name   kpl  
0       1  chevrolet chevelle malibu  7.65  
1       1          buick skylark 320  6.38  
2       1         plymouth satellite  7.65  


### 3-2 자료형 변환

In [5]:
#각 열의 자료형 확인
print(df.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model year        int64
origin            int64
name             object
kpl             float64
dtype: object


In [6]:
#horsepower 열의 고유값 확인
print(df['horsepower'].unique())

['130.0' '165.0' '150.0' '140.0' '198.0' '220.0' '215.0' '225.0' '190.0'
 '170.0' '160.0' '95.00' '97.00' '85.00' '88.00' '46.00' '87.00' '90.00'
 '113.0' '200.0' '210.0' '193.0' '?' '100.0' '105.0' '175.0' '153.0'
 '180.0' '110.0' '72.00' '86.00' '70.00' '76.00' '65.00' '69.00' '60.00'
 '80.00' '54.00' '208.0' '155.0' '112.0' '92.00' '145.0' '137.0' '158.0'
 '167.0' '94.00' '107.0' '230.0' '49.00' '75.00' '91.00' '122.0' '67.00'
 '83.00' '78.00' '52.00' '61.00' '93.00' '148.0' '129.0' '96.00' '71.00'
 '98.00' '115.0' '53.00' '81.00' '79.00' '120.0' '152.0' '102.0' '108.0'
 '68.00' '58.00' '149.0' '89.00' '63.00' '48.00' '66.00' '139.0' '103.0'
 '125.0' '133.0' '138.0' '135.0' '142.0' '77.00' '62.00' '132.0' '84.00'
 '64.00' '74.00' '116.0' '82.00']


In [7]:
import numpy as np
df['horsepower'].replace('?', np.nan, inplace=True) #'?' 을 np.nan으로 변경
df.dropna(subset=['horsepower'], axis=0, inplace=True) # 누락 데이터 행 삭제
df['horsepower']=df['horsepower'].astype('float') # 문자열을 실수형을 변환

#horsepower 열의 자료형 확인
print(df['horsepower'].dtypes)

float64


In [8]:
#origin 열의 고유값 확인
print(df['origin'].unique())

#정수형 데이터를 문자열 데이터로 변환
df['origin'].replace({1:'USA', 2:'EU', 3:'JPN'}, inplace=True)

#origin 열의 고유값과 자료형 확인
print(df['origin'].unique())
print(df['origin'].dtypes)

[1 3 2]
['USA' 'JPN' 'EU']
object


In [9]:
# 문자열을 범주형을 변환
# astype('category'): 범주형 데이터로 변환
df['origin']=df['origin'].astype('category')
print(df['origin'].dtypes)

#범주형을 문자열로 다시 변환
df['origin']=df['origin'].astype('str')
print(df['origin'].dtypes)

category
object


In [10]:
#model year 열의 정수형을 범주형으로 변환
print(df['model year'].sample(3))
df['model year']=df['model year'].astype('category')
print(df['model year'].sample(3))

182    76
313    80
213    76
Name: model year, dtype: int64
161    75
306    79
105    73
Name: model year, dtype: category
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]


## 5-4 범주형(카테고리) 데이터 처리

In [12]:
import pandas as pd
df=pd.read_csv('../data/part5/auto-mpg.csv', header=None)

df.columns=['mpg', 'cylinders','displacement','horsepower','weight','acceleration','model year','origin','name']

#horsepower 열의 누락 데이터('?')를 삭제하고 실수형으로 변환
df['horsepower'].replace('?', np.nan, inplace=True) #'?' 을 np.nan으로 변경
df.dropna(subset=['horsepower'],axis=0, inplace=True) #누락 데이터 행 삭제
df['horsepower']=df['horsepower'].astype('float') #문자열을 실수형으로 변환

#np.histogram 함수로 3개의 bin으로 구분할 경계값의 리스트 구하기
count, bin_dividers=np.histogram(df['horsepower'], bins=3)
print(bin_dividers)

[ 46.         107.33333333 168.66666667 230.        ]


In [13]:
# 3개의 bin에 이름 지정
bin_names=['저출력', '보통출력','고출력']
# pd.cut 함수로 각 데이터를 3개의 bin에 할당
df['hp_bin']=pd.cut(x=df['horsepower'], #데이터 배열
                    bins=bin_dividers,  #경계값 리스트
                    labels=bin_names,   #bin이름
                    include_lowest=True)#첫 경계값 포함

#horsepower 열, hp_bin 열의 첫 15행 출력
print(df[['horsepower', 'hp_bin']].head(15))

    horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력


## 4-2 더미 변수

In [14]:
# 3개의 bin에 이름 지정
bin_names=['저출력', '보통출력','고출력']
# pd.cut 함수로 각 데이터를 3개의 bin에 할당
df['hp_bin']=pd.cut(x=df['horsepower'], #데이터 배열
                    bins=bin_dividers,  #경계값 리스트
                    labels=bin_names,   #bin이름
                    include_lowest=True)#첫 경계값 포함

#hp_bin 열의 범주형 데이터를 더미 변수를 변환
horsepower_dummies=pd.get_dummies(df['hp_bin'])
print(horsepower_dummies.head(15))

    저출력  보통출력  고출력
0     0     1    0
1     0     1    0
2     0     1    0
3     0     1    0
4     0     1    0
5     0     0    1
6     0     0    1
7     0     0    1
8     0     0    1
9     0     0    1
10    0     0    1
11    0     1    0
12    0     1    0
13    0     0    1
14    1     0    0


In [16]:
##원핫인코딩
from sklearn import preprocessing

#전처리를 위한 encoder 객체 만둘기
label_encoder=preprocessing.LabelEncoder()  #label encoder 생성
onehot_encoder=preprocessing.OneHotEncoder() #one hot encoder 생성

#label encoder로 문자열 범주를 숫자형 범주로 변환
onehot_labeled=label_encoder.fit_transform(df['hp_bin'].head(15))
print(onehot_labeled)
print(type(onehot_labeled))

#2차원 행렬로 변경
onehot_reshaped=onehot_labeled.reshape(len(onehot_labeled), 1)
print(onehot_reshaped)
print(type(onehot_reshaped))

#희소행렬로 변환
onehot_fitted=onehot_encoder.fit_transform(onehot_reshaped)
print(onehot_fitted)
print(type(onehot_fitted))

[1 1 1 1 1 0 0 0 0 0 0 1 1 0 2]
<class 'numpy.ndarray'>
[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [2]]
<class 'numpy.ndarray'>
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 2)	1.0
<class 'scipy.sparse._csr.csr_matrix'>
